### ISSUE TITLE
Closing mutator tags when applicable.

### ISSUE THREAD

**Issue by acureau** [am-nobody/hte#4]
To restrict a mutator's effect to a defined area of input.

**Comment by Anirudh-GH** [comment]
Can i work on this issue?
But I need more details

**Comment by acureau** [comment]
> Can i work on this issue?
> But I need more details

Sure man, it was just an idea of mine. Have you looked into how the mutators work?
So when [M]5+5 is input, it will be changed to 10. However I'd like to be able to confine a 
tag to a smaller area rather than evaluating the entire input string.

Ex. My Number: [M]5+5[/M]

**Comment by Anirudh-GH** [comment]
Yeah I understood how mutators work but I can't fully understand what labels are. It will be helpful if you can give me an example.

Also the closing tags acts like parenthesis right?

Ex: [M][M]5+5[/M]*2 => (5+5)*2 = 20

**Comment by acureau** [comment]
> Yeah I understood how mutators work but I can't fully understand what labels are. It will be helpful if you can give me an example.
> 
> Also the closing tags acts like parenthesis right?
> 
> Ex: [M][M]5+5[/M]*2 => (5+5)*2 = 20

The label is the field shown to the user, it's the first thing defined in the .config on each line.
Label:(KEY)

The "Label" would be shown to the user and the "(KEY)" would be placed inside an HTML file and replaced by what the user inputs for that label. Yes the closing tags will act like parenthesis. The only purpose they will serve is to restrict the area which is mutated. Right now the [M] mutator will attempt to compute the entire input string. Which doesn't turn out well if there's more than just some numbers.
